# Generated by Django 5.2.8 on 2025-12-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField()),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Login',
            },
        ),
    ]
