# Generated by Django 5.2.8 on 2026-02-11 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote_analysis_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis_vote',
            options={'verbose_name': 'Analysis_vote', 'verbose_name_plural': 'Analysis_vote'},
        ),
    ]
