# Generated by Django 5.2.8 on 2026-02-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=255)),
                ('numbers', models.IntegerField()),
                ('emails', models.EmailField(max_length=254)),
                ('passwords', models.CharField()),
            ],
        ),
    ]
